# ================================================================================================================================
# The configurations below are used to connect to the Config Server (dl-config-server) and get the configurations from the dl-config-server-repo.
# The configurations are stored in the dl-config-server-repo in the dl-notification-service.properties file.
# ================================================================================================================================
spring:
    config:
        # The 'configserver:' is used to tell the application to look for the configurations in the Config Server.
        # The 'optional' prefix is used to tell the application that if the Config Server is not available, it should use the configurations in this application.yaml file (need to uncomment them).
        # import:  'optional:configserver:'
        import: 'configserver:'
    cloud:
        config:
            discovery:
                serviceId: dl-config-server
            # The username and password are used to access the Config Server (basic authentication) as it is now using Spring Security.
            username: admin
            password: 'admin'
